import Head from "next/head";
import { AppBar } from "../components/appBar";
import { BottonNavigation } from "../components/bottonNavigation";
import { Container } from "../components/container";
import { Lists } from "../components/lists";

export default function AddToList() {
  return (
    <>
      <Head>
        <title>CompreBEM</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <AppBar left={<AppBar.Back />} />

      <Container>
        <Lists />
      </Container>
      <BottonNavigation />
    </>
  );
}
