import Head from "next/head";
import { AppBar } from "../components/appBar";
import { BottonNavigation } from "../components/bottonNavigation";
import { Container } from "../components/container";
import { ProductCardProps } from "../components/productCard";
import { Section } from "../components/section";

export default function Home() {
  const pereciveis: Omit<ProductCardProps, "color">[] = [
    {
      id: "1",
      title: "Arroz Tio João - 5kg",
      description: "Promoção para 10 até pacotes.",
      price: 25.99,
    },
    {
      id: "2",
      title: "Feijao Kicaldo - 2kg",
      description: "Enquanto durar o estoque.",
      price: 25.99,
    },
    {
      id: "3",
      title: "Óleo de Soja - 900ml",
      description: "Promoção para 10 pacotes.",
      price: 25.99,
    },
  ];

  const higiene: Omit<ProductCardProps, "color">[] = [
    {
      id: "4",
      title: "Arroz Tio João - 5kg",
      description: "Promoção para 10 até pacotes.",
      price: 25.99,
    },
    {
      id: "5",
      title: "Feijao Kicaldo - 2kg",
      description: "Enquanto durar o estoque.",
      price: 25.99,
    },
    {
      id: "6",
      title: "Óleo de Soja - 900ml",
      description: "Promoção para 10 pacotes.",
      price: 25.99,
    },
  ];

  const limpeza: Omit<ProductCardProps, "color">[] = [
    {
      id: "7",
      title: "Arroz Tio João - 5kg",
      description: "Promoção para 10 até pacotes.",
      price: 25.99,
    },
    {
      id: "8",
      title: "Feijao Kicaldo - 2kg",
      description: "Enquanto durar o estoque.",
      price: 25.99,
    },
    {
      id: "9",
      title: "Óleo de Soja - 900ml",
      description: "Promoção para 10 pacotes.",
      price: 25.99,
    },
  ];

  const hortifruit: Omit<ProductCardProps, "color">[] = [
    {
      id: "10",
      title: "Arroz Tio João - 5kg",
      description: "Promoção para 10 até pacotes.",
      price: 25.99,
    },
    {
      id: "11",
      title: "Feijao Kicaldo - 2kg",
      description: "Enquanto durar o estoque.",
      price: 25.99,
    },
    {
      id: "12",
      title: "Óleo de Soja - 900ml",
      description: "Promoção para 10 pacotes.",
      price: 25.99,
    },
  ];

  return (
    <>
      <Head>
        <title>CompreBEM</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <AppBar content={<AppBar.Logo />} withFilter />

      <Container small>
        <Section title="Perecíveis" color="#1569B7" products={pereciveis} />
        <Section title="Higiene Pessoal" color="#C93838" products={higiene} />
        <Section title="Limpeza" color="#27893C" products={limpeza} />
        <Section title="Hortifruit" color="#E37A1A" products={hortifruit} />
      </Container>
      <BottonNavigation />
    </>
  );
}
