import Head from "next/head";
import { AppBar } from "../components/appBar";
import { BottonNavigation } from "../components/bottonNavigation";
import { Carousel } from "../components/carousel";
import { Container } from "../components/container";
import { Title } from "../components/title";

export default function Home() {
  return (
    <>
      <Head>
        <title>CompreBEM</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <AppBar
        left={<AppBar.Back />}
        content={<AppBar.Logo />}
        right={<AppBar.Cancel />}
        withFilter
      />

      <Container small>
        <Title name="Perecíceis" />
        <Carousel />
        <Title name="Higiene Pessoal" />
        <Carousel />
        <Title name="Limpeza" />
        <Carousel />
      </Container>
      <BottonNavigation />
    </>
  );
}
